---
# defaults file for instance

# Default instance provider (Google Compute Engine)
instance_provider: gce

# A list of instance node names.
# Names must start with a lowercase letter followed by up to 63 lowercase letters,
# numbers, or hyphens, and cannot end with a hyphen
instance_nodes: {}
#  - node-001
#  - node-002

# A zone is an isolated location within a region.
# Resources that live in a zone, such as instances,
# are referred to as zonal resources
instances_zone: europe-west1-b

# Predefined machine type which managed by cloud provider:
instance_type: n1-standard-1

# Each instance requires a disk to boot from.
# Specify an image when you create an instance.
instance_image: centos-7
