---
# tasks file for users

- name: Create groups
  group:
    name: '{{ item.name }}'
  when: item.create is not defined or item.create
  with_items: '{{ users_data }}'

- name: Create users
  user:
    name: '{{ item.name }}'
    group: '{{ item.name }}'
    groups: '{{ item.name }}{% if item.admin is defined and item.admin %},wheel{% endif %}'
    generate_ssh_key: yes
  when: item.create is not defined or item.create
  with_items: '{{ users_data }}'

- name: Setup home directory
  user:
    name: '{{ item.name }}'
    home: '{{ item.home }}'
    move_home: yes
  when: item.home is defined and item.home != ''
  with_items: '{{ users_data }}'

- name: Setup sudoers
  template:
    src: '{% if item.admin is defined and item.admin %}admin-{% endif %}sudoers.j2'
    dest: /etc/sudoers.d/1{% if item.admin is defined and item.admin %}7{% else%}8{% endif %}-{{ item.name }}
    mode: 0440
  with_items: '{{ users_data }}'

- name: Added bashrc data
  lineinfile:
    dest: '{% if item.0.home is defined and item.0.home != "" %}{{ item.0.home }}{% else %}/home/{{ item.0.name }}{% endif %}/.bashrc'
    regexp: '^{{ item.1 }}'
    line: '{{ item.1 }}'
  with_subelements:
    - '{{ users_data }}'
    - bashrc
    - skip_missing: yes

- name: Command line prompt
  lineinfile:
    dest: '{% if item.home is defined and item.home != "" %}{{ item.home }}{% else %}/home/{{ item.name }}{% endif %}/.bashrc'
    regexp: "^PS1="
    line: 'PS1="\n\[\e[32;1m\](\[\e[36;1m\]\t\[\e[32;1m\])-(\[\e[37;1m\]\u @ \H\[\e[32;1m\])-(\[\e[33;1m\]\w\[\e[32;1m\])\n$ \[\e[0m\]"'
  when: item.homeless is not defined or not item.homeless
  with_items: '{{ users_data }}'
