---
- hosts: all:!localhost
  remote_user: '{{ cloud_ops_superuser }}'
  become: true

  roles:
    - role: firewall
      firewall_zones: '{{ cloud_services_access }}'
      when: cloud_services_access is defined and (cloud_services_access|length>0)
