---
- hosts: all:!localhost
  remote_user: '{{ cloud_ssh_superuser }}'
  become: true

  roles:
    - role: permissions
      addmission_group:
        - name: '{{ cloud_ssh_superuser }}'
          ips: '{{ cloud_ssh_allowed_ips }}'

  tasks:

    - name: Add permissions for specified users
      include_role:
        name: permissions
      vars:
        addmission_group:
          - name: '{{ cloud_ssh_user.name }}'
            ips: '{{ cloud_ssh_allowed_ips }}'
      with_items: '{{ cloud_ssh_users }}'
      loop_control:
        loop_var: cloud_ssh_user
