---
- hosts: all:!localhost
  remote_user: '{{ cloud_ssh_user }}'
  become: true

  roles:
    - role: permissions
      permissions_users:
        - name: '{{ cloud_ssh_user }}'
          ips: '{{ cloud_ssh_allowed_ips }}'
        - name: '{{ cloud_dev_ssh_user }}'
          ips: '{{ cloud_ssh_allowed_ips }}'
