---
- hosts: all:!localhost
  remote_user: '{{ cloud_ssh_user }}'
  become: true

  tasks:
  - name: Update CentOS packages
    yum:
      name: '*'
      state: latest
    notify:
      - reboot vps
      - wait to come up
    when: ansible_distribution == 'CentOS'
 
  handlers:

    - name: reboot vps
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0

    - name: wait to come up
      wait_for:
        host: '{{ ansible_host }}'
        port: 22
        delay: 90
      delegate_to: localhost
      become: false
