---
# tasks file for permissions

- name: Add ssh access for specified users and allowed hosts
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers {{ item.0.name }}@{{ item.1 }}"
    line: "AllowUsers {{ item.0.name }}@{{ item.1 }}"
  with_subelements:
    - "{{ addmission_group }}"
    - ips
  notify:
    - restart sshd
