- import_playbook: setup/update.yml
- import_playbook: setup/firewall.yml
- import_playbook: setup/permissions.yml
- import_playbook: setup/users.yml
- import_playbook: setup/ntp.yml
- import_playbook: setup/logs-rotation.yml
