---
# handlers file for update

- name: reboot vps
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0

- name: wait to come up
  wait_for:
    host: '{{ ansible_host }}'
    port: 22
    delay: 90
  delegate_to: localhost
  become: false
